jtype: BertReRanker
with:
  model_name: skt/kobert-base-v1
  max_seq_len: 256
  batch_size: 64
  max_epochs: 2
  gpus: 1
metas:
  name: bert_ranker
  description: BERT ranking on top-k
  py_modules: bert_reranker.py

