!KoBARTRegEncoder
metas:
  batch_size: 32
  on_gpu: True
  py_modules: custom_executors_sentencekobart.py
requests:
  on:
    [SearchRequest, IndexRequest]:
      with:
        traversal_paths: ['c']
      drivers:
        - jtype: EncodeDriver {}    # we need EncodeDriver for encoder